#spark.master: spark://my-spark-master:7077
#cassandra.host: my-cassandra-cassandr-0.my-cassandra-cassandr.default.svc.cluster.local,my-cassandra-cassandr-1.my-cassandra-cassandr.default.svc.cluster.local
#cassandra.keyspace: hfcb

spark.master: spark://master:7077
cassandra.host: 192.168.1.140
cassandra.keyspace: hfcb